/*
  HostMidiCcTest.h

  Covers the fix for: CC generated by a MIDI FX / modulator plugin placed ahead of
  XpandrLink in a DAW's own plugin chain (e.g. Logic's Modulator) never reached the
  CC-map -- XpandrLinkAudioProcessor::processBlock discarded the host's MidiBuffer
  entirely. Host *parameter automation* worked (a separate path, via
  AudioProcessorParameter::Listener), which is why that symptom looked inconsistent.

  MidiEngine::pushHostControllerValue(cc, value) is the realtime-safe entry point
  processBlock calls from the audio thread: a plain atomic store into
  pendingHostCc_, no lock, no syscall. MidiEngine::timerCallback (already running
  every 5ms on the message thread) drains any pending values through the same
  applyCcMapping() logic the external-MIDI-input CC path already used, and fires
  the same onParameterChangedFromHardware callback. drainSendQueueForTest() drives
  that same timerCallback() deterministically, so no live Timer pump is needed here.

  Verifies: NFR-HW-03 (CC automation interception), extended to the host-buffer path.
*/
#pragma once
#include <JuceHeader.h>
#include "../Engine/MidiEngine.h"
#include "../Engine/SynthDefs.h"
#include "../Data/XpanderData.h"
#include "MockMidiBackend.h"

class HostMidiCcTest : public juce::UnitTest
{
public:
    HostMidiCcTest() : juce::UnitTest("Host MIDI CC (plugin-chain buffer)", "MidiEngine") {}

    struct CaptureListener : public MidiEngine::Listener
    {
        int paramCalls = 0;
        int lastPage = -1, lastParamCol = -1, lastValue = 0;

        void onMidiActivity(bool) override {}
        void onPatchReceived(const std::vector<uint8_t>&, int) override {}
        void onParameterChangedFromHardware(int page, int paramCol, int value, bool, bool) override
        {
            ++paramCalls; lastPage = page; lastParamCol = paramCol; lastValue = value;
        }
        void onStatusUpdate(const juce::String&) override {}
    };

    void runTest() override
    {
        beginTest("Pushing a host CC value does not broadcast until the queue is drained");
        {
            MidiEngine engine;
            CaptureListener l;
            engine.addListener(&l);
            engine.setCcMap(10, 0); // id=0: page=PAGE_VCO1, paramCol=VCO_FREQ, min=0, max=63

            engine.pushHostControllerValue(10, 64);
            expectEquals(l.paramCalls, 0, "should not fire synchronously from the audio-thread push");

            engine.removeListener(&l);
        }

        beginTest("A mapped host CC is scaled and dispatched once drained -- same result as the external-input path");
        {
            MidiEngine engine;
            CaptureListener l;
            engine.addListener(&l);
            engine.setCcMap(10, 0);

            engine.pushHostControllerValue(10, 64);
            engine.drainSendQueueForTest();

            expectEquals(l.paramCalls, 1);
            expectEquals(l.lastPage, (int)Matrix12::PAGE_VCO1);
            expectEquals(l.lastParamCol, (int)Matrix12::VCO_FREQ);
            expectEquals(l.lastValue, (int)std::round(64.0 * 63.0 / 127.0));

            engine.removeListener(&l);
        }

        beginTest("An unmapped host CC does nothing, even after drain");
        {
            MidiEngine engine;
            CaptureListener l;
            engine.addListener(&l);

            engine.pushHostControllerValue(77, 100); // never mapped
            engine.drainSendQueueForTest();

            expectEquals(l.paramCalls, 0);
            engine.removeListener(&l);
        }

        beginTest("A burst of pushes to the same CC before a drain only broadcasts the LATEST value");
        {
            MidiEngine engine;
            CaptureListener l;
            engine.addListener(&l);
            engine.setCcMap(10, 0);

            for (int v = 0; v <= 127; ++v)
                engine.pushHostControllerValue(10, v);
            engine.drainSendQueueForTest();

            expectEquals(l.paramCalls, 1, "only the final pushed value should survive to the drain");
            expectEquals(l.lastValue, (int)std::round(127.0 * 63.0 / 127.0));

            engine.removeListener(&l);
        }

        beginTest("Out-of-range CC numbers are ignored, not clamped into a real slot");
        {
            MidiEngine engine;
            CaptureListener l;
            engine.addListener(&l);
            engine.setCcMap(10, 0);

            engine.pushHostControllerValue(-1, 64);
            engine.pushHostControllerValue(128, 64);
            engine.drainSendQueueForTest();

            expectEquals(l.paramCalls, 0);
            engine.removeListener(&l);
        }

        beginTest("Two different mapped CCs pushed together both survive one drain");
        {
            MidiEngine engine;
            CaptureListener l;
            engine.addListener(&l);
            engine.setCcMap(10, 0);
            engine.setCcMap(11, 1); // id=1: next VCO1 param, whatever it is

            engine.pushHostControllerValue(10, 64);
            engine.pushHostControllerValue(11, 32);
            engine.drainSendQueueForTest();

            expectEquals(l.paramCalls, 2);
            engine.removeListener(&l);
        }

        // Found via real-world Logic testing (2026-09-21): a mapped CC updated the editor's
        // on-screen knob but never reached actual hardware. Root cause is pre-existing, not
        // specific to the host-buffer path: applyCcMapping only ever called
        // broadcastParameterChange (UI-only), which EditorTabComponent::onParameterChangedFromHardware
        // applies under setHardwareUpdateMode(true) -- the same guard that makes
        // sendParameterToSynth() a no-op, since it exists specifically to stop a genuine
        // hardware-echoed value from being re-sent. A CC from a controller/DAW is not an echo --
        // it's a new value that needs to reach the synth, same as a UI knob drag. This exercises
        // applyCcMapping's real send path via a MockMidiBackend, independent of the UI.
        beginTest("A mapped CC actually reaches the synth output, not just the on-screen display");
        {
            auto mockPtr = std::make_unique<MockMidiBackend>();
            auto& mock = *mockPtr;
            MidiEngine engine{ std::move(mockPtr) };
            engine.setMidiOutput("Fake Synth");
            engine.setCcMap(40, 40); // id=40: page=PAGE_VCF, paramCol=VCF_FREQ, min=0, max=127

            engine.pushHostControllerValue(40, 64);
            // Page-select settles before the parameter byte follows it (0ms after) -- pump for
            // the full window regardless of when the first message appears, same pattern as
            // MidiEngineSendPathTest::pumpSendQueue (stopping at the first non-empty check would
            // catch only the page-select and miss the param-change queued right behind it).
            for (int elapsed = 0; elapsed < 400; elapsed += 10)
            {
                engine.drainSendQueueForTest();
                juce::Thread::sleep(10);
            }
            engine.drainSendQueueForTest();

            bool sawParamChange = false;
            for (auto& m : mock.sentMessages)
            {
                if (!m.isSysEx() || m.getSysExDataSize() < 10) continue;
                auto* d = m.getSysExData();
                if (d[2] == 0x0A && d[4] == (uint8_t)Matrix12::VCF_FREQ)
                {
                    sawParamChange = true;
                    int sentVal = (int)d[8] | ((int)d[9] << 7);
                    expectEquals(sentVal, (int)std::round(64.0 * 127.0 / 127.0));
                }
            }
            expect(sawParamChange, "expected a param-change SysEx (cmd=0x0A) for VCF_FREQ to reach the mock output");
        }

        // A real Matrix-12 locked up during testing (2026-09-21) with a continuously-running
        // Modulator LFO feeding CC -- confirms the flood-protection half of the fix, not just
        // the threading half above. Simulates a sustained CC source by pushing many distinct
        // values across several drain cycles (matching how pendingHostCc_ actually gets fed --
        // one push per audio block/timer tick, not a single burst before any drain) and asserts
        // the number of param-change SysEx that actually reach hardware is tiny relative to the
        // number of distinct values pushed, same "only the settled value survives" property
        // ModAmountCoalesceTest.h already proved for mod-matrix amount drags.
        beginTest("A continuously-changing CC source (e.g. a DAW MIDI FX LFO) does not flood the synth output");
        {
            auto mockPtr = std::make_unique<MockMidiBackend>();
            auto& mock = *mockPtr;
            MidiEngine engine{ std::move(mockPtr) };
            engine.setMidiOutput("Fake Synth");
            engine.setCcMap(40, 40); // id=40: page=PAGE_VCF, paramCol=VCF_FREQ

            // 40 drain ticks, a new (different) CC value pushed before each one -- simulates
            // an LFO changing faster than the throttle window (kCcSendThrottleMs) alongside
            // this test's own real-time drain cadence.
            for (int i = 0; i < 40; ++i)
            {
                engine.pushHostControllerValue(40, (i * 7) % 128);
                engine.drainSendQueueForTest();
                juce::Thread::sleep(5);
            }
            // Let the final throttle window fully elapse so the last settled value flushes.
            for (int elapsed = 0; elapsed < 200; elapsed += 10)
            {
                engine.drainSendQueueForTest();
                juce::Thread::sleep(10);
            }
            engine.drainSendQueueForTest();

            int paramChangeCount = 0;
            for (auto& m : mock.sentMessages)
            {
                if (m.isSysEx() && m.getSysExDataSize() >= 10 && m.getSysExData()[2] == 0x0A)
                    ++paramChangeCount;
            }
            expect(paramChangeCount > 0, "at least the final settled value must still reach the synth");
            // Threshold deliberately generous, not tuned to this machine's exact scheduling:
            // Thread::sleep(5) has no hard real-time guarantee, and CI runners (especially
            // under ASan/TSan instrumentation) observed 15-19 here versus a tighter local
            // number -- the point is proving the throttle engages at all (well under one
            // send per push), not pinning an exact count.
            expect(paramChangeCount < 30,
                   "40 distinct pushes over ~200ms must not produce anywhere near 40 sends -- got "
                   + juce::String(paramChangeCount));
        }

        // Found via real-world Logic testing (2026-09-22): two MIDI FX plugins mapped to
        // parameters on DIFFERENT pages (CC3 -> VCF Freq, CC4 -> VCO1 Freq), both continuously
        // running, caused rapid alternating page-switching on the hardware -- a real risk of
        // repeating the earlier lockup, since each switch needs its own page-select + settle
        // and an independent per-CC throttle doesn't bound their COMBINED rate. The throttle
        // gate is now shared across all CCs (see lastCcSendTime_ in MidiEngine.h) so the
        // aggregate send rate stays bounded regardless of how many CCs are concurrently
        // active; pendingCcSend_ stays per-CC so neither one is starved by the other.
        beginTest("Two CCs mapped to DIFFERENT pages, both continuously active, share one throttle "
                  "(bounded aggregate rate) without starving either one");
        {
            auto mockPtr = std::make_unique<MockMidiBackend>();
            auto& mock = *mockPtr;
            MidiEngine engine{ std::move(mockPtr) };
            engine.setMidiOutput("Fake Synth");
            engine.setCcMap(3, 40); // id=40: page=PAGE_VCF,  paramCol=VCF_FREQ
            engine.setCcMap(4, 0);  // id=0:  page=PAGE_VCO1, paramCol=VCO_FREQ

            for (int i = 0; i < 30; ++i)
            {
                engine.pushHostControllerValue(3, (i * 5) % 128);
                engine.pushHostControllerValue(4, (i * 11) % 128);
                engine.drainSendQueueForTest();
                juce::Thread::sleep(5);
            }
            for (int elapsed = 0; elapsed < 400; elapsed += 10)
            {
                engine.drainSendQueueForTest();
                juce::Thread::sleep(10);
            }
            engine.drainSendQueueForTest();

            int vcfSends = 0, vco1Sends = 0, totalParamChanges = 0;
            for (auto& m : mock.sentMessages)
            {
                if (!m.isSysEx() || m.getSysExDataSize() < 10 || m.getSysExData()[2] != 0x0A) continue;
                ++totalParamChanges;
                auto paramCol = m.getSysExData()[4];
                if (paramCol == (uint8_t)Matrix12::VCF_FREQ) ++vcfSends;
                if (paramCol == (uint8_t)Matrix12::VCO_FREQ) ++vco1Sends;
            }

            expect(vcfSends > 0,  "the VCF-mapped CC must not be starved by the VCO1-mapped one");
            expect(vco1Sends > 0, "the VCO1-mapped CC must not be starved by the VCF-mapped one");
            // ~150ms shared throttle over ~550ms total real time -- roughly 4-5 sends possible
            // if perfectly paced; generous upper bound for scheduling variance, but still far
            // below what two INDEPENDENTLY-throttled 50ms streams would have produced (~20+).
            expect(totalParamChanges < 15,
                   "two concurrently-active different-page CCs must not roughly double the "
                   "single-CC send rate -- got " + juce::String(totalParamChanges) + " total sends");
        }
    }
};

static HostMidiCcTest hostMidiCcTestInstance;
